In [48]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

In [49]:
dset = pd.read_csv ('new.csv')
dset.keys()

Index(['age', 'HE_sbp', 'HE_wc', 'HE_BMI', 'HE_chol', 'HE_HDL_st2', 'N_FAT'], dtype='object')

In [50]:
df=pd.DataFrame(dset)
df=df.replace(' ', np.NaN)
df


age HE_sbp  HE_wc            HE_BMI HE_chol HE_HDL_st2             N_FAT
0      30    104   81.9  28.9398577909837     184     51.552  57.7223486977762
1      56    116     84  28.4007126790205     NaN        NaN  48.9471946015806
2      29    131   85.5  28.6597082714648     191     43.936  100.764834735342
3      65    132     71  20.1882379149031     133     30.608  39.5014208507789
4      57    113   63.3  19.4215435985507     168     46.792               NaN
...   ...    ...    ...               ...     ...        ...               ...
7545   30    132  103.1  29.5073251417769     181      60.12  20.0093110656924
7546   55    122   96.3  28.4453713327845     225     61.072  15.5394723269073
7547   58    151    111  31.8538712257376     201     47.744  13.1507548420675
7548   63    141   84.2  25.0715776569083     189      64.88  71.4495547027698
7549   71    162   95.1  26.6766697951351     161     37.272  59.8136551723254

[7550 rows x 7 columns]

In [51]:
df=df.dropna()

In [52]:
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(df)



StandardScaler()

In [53]:
scaled_data=scaler.transform(df)

scaled_data


array([[-0.9234382 , -0.78012281,  0.18808397, ..., -0.01036123,
         0.02442673,  0.37802027],
       [-0.97615518,  0.89631105,  0.53853695, ...,  0.19117552,
        -0.62212434,  1.6033877 ],
       [ 0.92165592,  0.95840119, -0.87300979, ..., -1.47870038,
        -1.75358871, -0.14070747],
       ...,
       [ 0.55263709,  2.1381139 ,  3.02091226, ...,  0.47908515,
        -0.29884881, -0.890879  ],
       [ 0.81622197,  1.51721247,  0.41198449, ...,  0.13359359,
         1.15589109,  0.76881719],
       [ 1.23795777,  2.82110547,  1.47307824, ..., -0.67255339,
        -1.18785652,  0.43755723]])

In [54]:
from sklearn.decomposition import PCA

pca=PCA(n_components=2)

pca.fit(scaled_data)


PCA(n_components=2)

In [55]:
x_pca=pca.transform(scaled_data)

scaled_data.shape

(4910, 7)

In [56]:
x_pca.shape

(4910, 2)

In [57]:
x_pca

array([[ 0.16755471,  1.28100501],
       [ 0.95461436,  1.89309884],
       [-0.04539937,  0.11998183],
       ...,
       [ 4.24101458,  0.30795332],
       [ 0.97953401, -0.55182231],
       [ 2.95482148,  0.54578694]])

In [58]:
import sklearn.decomposition.pca
back=pca.inverse_transform(x_pca)


In [59]:
diff=scaled_data-back
diff

array([[-0.44921834, -0.57362428, -0.23779755, ...,  0.41510213,
         0.62836915, -0.29214342],
       [-0.55694929,  0.92947722, -0.4781406 , ...,  0.67473645,
         0.45236539,  0.72603232],
       [ 0.99040659,  1.00124648, -0.87943156, ..., -1.42630365,
        -1.7127464 , -0.21324347],
       ...,
       [-1.00657154,  0.57161499,  0.61733005, ..., -0.28135297,
         0.92753846, -0.38041339],
       [ 0.19302934,  1.02363518,  0.01930534, ..., -0.26567827,
         1.16642234,  1.22564313],
       [ 0.29149317,  1.79974854, -0.28794413, ..., -1.08346045,
        -0.18839191,  0.61300164]])

In [61]:

mse = ((scaled_data - back)**2).mean(axis=None)
mse

0.44872807661062364